### ISSUE TITLE
Update the examples

### ISSUE THREAD

**Issue by jtpio** [jtpio/jupyterlab-extension-examples#14]
Most of the examples were updated to work with JupyterLab 1, but another pass is needed to:

- use consistent naming (plugin ids, variable names and so on)
- follow the code style (#4)
- make sure they behave as intended (they compile but it doesn't mean they still work)
- deprecate the use of `VDomRenderer` in favor of React
- update explanations and screenshots / screencasts

List of examples to be updated:

- [x] advanced/kernel-messaging #57 
- [x] advanced/kernel-output #58 
- [x] advanced/serving-files #56 
- [x] basics/datagrid #52 
- [x] basics/hello-world #21
- [x] basics/signals #34 #53 
- [x] context-menu/menus #39 
- [x] widget-tracker/jupyter-widgets #62 
- [x] widget-tracker/widgets #59

**Comment by jtpio** [comment]
We can also open one new issue per example so it's easier to make progress.

**Comment by jtpio** [comment]
Thanks @fcollonval for going through the examples!

Do you think we should close this issue?

**Comment by fcollonval** [comment]
I think we are good for this one, thanks for the reviews.
